Test

diff --git a/integtest/Makefile b/integtest/Makefile
--- a/integtest/Makefile
+++ b/integtest/Makefile
@@ -23,7 +23,8 @@ check: \
 	relative_conf_file \
 	keep_hash \
 	sub_dir \
-	keep_hash_and_sub_dir
+	keep_hash_and_sub_dir \
+	multi_branch
 
 .PHONY: style
 style: html_diff
@@ -162,6 +163,7 @@ keep_hash:
 		--target_repo $(TMP)/dest.git \
 		--conf $(TMP)/conf.yaml \
 		--keep_hash | tee $(TMP)/out
+	$(call GREP_V,'Test book',$(TMP)/out)
 	$(call GREP,'No changes to push',$(TMP)/out)
 
 	# We expact the same files as the minimal because we the changes that we
@@ -188,8 +190,10 @@ sub_dir:
 	/docs_build/build_docs.pl --in_standard_docker --all --push \
 		--target_repo $(TMP)/dest.git \
 		--conf $(TMP)/conf.yaml \
-		--sub_dir source:master:$(TMP)/to_sub
-
+		--sub_dir source:master:$(TMP)/to_sub | tee $(TMP)/out
+	$(call GREP,'Test book: Building master...',$(TMP)/out)
+	$(call GREP,'Test book: Finished master',$(TMP)/out)
+	$(call GREP,'Test book: Copying master to current',$(TMP)/out)
 	$(call MINIMAL_ALL_EXPECTED_FILES,'local changes')
 
 .PHONY: keep_hash_and_sub_dir
@@ -206,7 +210,11 @@ keep_hash_and_sub_dir:
 	sed 's|--tmp--|$(TMP)|' two_repos_conf.yaml > $(TMP)/conf.yaml
 	/docs_build/build_docs.pl --in_standard_docker --all --push \
 		--target_repo $(TMP)/dest.git \
-		--conf $(TMP)/conf.yaml
+		--conf $(TMP)/conf.yaml | tee $(TMP)/out
+	$(call GREP,'Test book: Building master...',$(TMP)/out)
+	$(call GREP,'Test book: Finished master',$(TMP)/out)
+	$(call GREP,'Test book: Copying master to current',$(TMP)/out)
+	$(call GREP,'Pushing changes',$(TMP)/out)
 
 	# Move a "bad" file into source2 so we can be sure we're not picking it up
 	cp ../README.asciidoc $(TMP)/source2/index.asciidoc
@@ -217,8 +225,9 @@ keep_hash_and_sub_dir:
 	/docs_build/build_docs.pl --in_standard_docker --all --push \
 		--target_repo $(TMP)/dest.git \
 		--conf $(TMP)/conf.yaml \
-		--keep_hash | tee /tmp/out
-	$(call GREP,'No changes to push',/tmp/out)
+		--keep_hash | tee $(TMP)/out
+	$(call GREP_V,'Test book',$(TMP)/out)
+	$(call GREP,'No changes to push',$(TMP)/out)
 
 	# Setup the directory we'd like to substitute
 	mkdir -p $(TMP)/to_sub/docs
@@ -229,10 +238,83 @@ keep_hash_and_sub_dir:
 		--target_repo $(TMP)/dest.git \
 		--conf $(TMP)/conf.yaml \
 		--keep_hash --sub_dir source1:master:$(TMP)/to_sub | tee $(TMP)/out
+	$(call GREP,'Test book: Building master...',$(TMP)/out)
+	$(call GREP,'Test book: Finished master',$(TMP)/out)
+	$(call GREP,'Test book: Copying master to current',$(TMP)/out)
 	$(call GREP,'Pushing changes',$(TMP)/out)
 
 	git clone $(TMP)/dest.git $(TMP)/dest
 	$(call GREP,'extra extra extra',$(TMP)/dest/html/test/current/_chapter.html)
+
+.PHONY: multi_branch
+multi_branch:
+	# Tests for how we rebuild books with multiple branches
+
+	# When the book hasn't been built before we build all branches
+	rm -rf $(TMP)
+	$(call INIT_REPO_WITH_FILE,$(TMP)/source,minimal.asciidoc,docs/index.asciidoc)
+	cd $(TMP)/source && git checkout -b prev
+	git init --bare $(TMP)/dest.git
+
+	sed 's|--tmp--|$(TMP)|' multi_branch.yaml > $(TMP)/conf.yaml
+	/docs_build/build_docs.pl --in_standard_docker --all --push \
+		--target_repo $(TMP)/dest.git \
+		--conf $(TMP)/conf.yaml | tee $(TMP)/out
+	$(call GREP,'Test book: Building master...',$(TMP)/out)
+	$(call GREP,'Test book: Finished master',$(TMP)/out)
+	$(call GREP,'Test book: Building prev...',$(TMP)/out)
+	$(call GREP,'Test book: Finished prev',$(TMP)/out)
+	$(call GREP,'Test book: Copying master to current',$(TMP)/out)
+	$(call GREP,'Test book: Writing versions TOC',$(TMP)/out)
+	$(call GREP,'Pushing changes',$(TMP)/out)
+
+	git clone $(TMP)/dest.git $(TMP)/dest
+	# The main index links to the current version
+	$(call GREP,'<a class="ulink" href="test/current/index.html" target="_top">Test book \[master\]</a>',$(TMP)/dest/html/index.html)
+	$(call GREP,'<a class="ulink" href="test/index.html" target="_top">other versions</a>',$(TMP)/dest/html/index.html)
+	# And the book's index links to all versions
+	$(call GREP,'<a class="ulink" href="current/index.html" target="_top">Test book: master (current)</a>',$(TMP)/dest/html/test/index.html)
+	$(call GREP,'<a class="ulink" href="prev/index.html" target="_top">Test book: prev</a>',$(TMP)/dest/html/test/index.html)
+	# And all versions have been built
+	[ -s $(TMP)/dest/html/test/current/index.html ]
+	[ -s $(TMP)/dest/html/test/master/index.html ]
+	[ -s $(TMP)/dest/html/test/prev/index.html ]
+
+	# When one of the non-current branches has changed we rebuild it but do not
+	# copy the current branch
+	cd $(TMP)/source && \
+		git checkout prev && \
+		echo "changed" >> docs/index.asciidoc && \
+		git add . && \
+		git commit -m "change"
+	/docs_build/build_docs.pl --in_standard_docker --all --push \
+		--target_repo $(TMP)/dest.git \
+		--conf $(TMP)/conf.yaml | tee $(TMP)/out
+	$(call GREP_V,'Test book: Building master...',$(TMP)/out)
+	$(call GREP_V,'Test book: Finished master',$(TMP)/out)
+	$(call GREP,'Test book: Building prev...',$(TMP)/out)
+	$(call GREP,'Test book: Finished prev',$(TMP)/out)
+	$(call GREP_V,'Test book: Copying master to current',$(TMP)/out)
+	$(call GREP,'Test book: Writing versions TOC',$(TMP)/out)
+	$(call GREP,'Pushing changes',$(TMP)/out)
+
+	# When the current branch has changed we rebuild it and copy it to the
+	# current branch
+	cd $(TMP)/source && \
+		git checkout master && \
+		echo "changed" >> docs/index.asciidoc && \
+		git add . && \
+		git commit -m "change"
+	/docs_build/build_docs.pl --in_standard_docker --all --push \
+		--target_repo $(TMP)/dest.git \
+		--conf $(TMP)/conf.yaml | tee $(TMP)/out
+	$(call GREP,'Test book: Building master...',$(TMP)/out)
+	$(call GREP,'Test book: Finished master',$(TMP)/out)
+	$(call GREP_V,'Test book: Building prev...',$(TMP)/out)
+	$(call GREP_V,'Test book: Finished prev',$(TMP)/out)
+	$(call GREP,'Test book: Copying master to current',$(TMP)/out)
+	$(call GREP,'Test book: Writing versions TOC',$(TMP)/out)
+	$(call GREP,'Pushing changes',$(TMP)/out)
 
 define GREP=
 	# grep for a string in a file, outputting the whole file if there isn't
@@ -267,7 +349,11 @@ define BUILD_MINIMAL_ALL=
 	$(SETUP_MINIMAL_ALL)
 	/docs_build/build_docs.pl --in_standard_docker --all --push \
 		--target_repo $(TMP)/dest.git \
-		--conf $(TMP)/conf.yaml
+		--conf $(TMP)/conf.yaml | tee $(TMP)/out
+	$(call GREP,'Test book: Building master...',$(TMP)/out)
+	$(call GREP,'Test book: Finished master',$(TMP)/out)
+	$(call GREP,'Test book: Copying master to current',$(TMP)/out)
+	$(call GREP,'Test book: Writing redirect to current branch...',$(TMP)/out)
 endef
 
 define MINIMAL_ALL_EXPECTED_FILES=
@@ -298,12 +384,27 @@ define GREP=
 	# grep for a string in a file, outputting the whole file if there isn't
 	# a match.
 	[ -e $(2) ] || { \
-		echo "can't find $(2)"; \
+		echo "can't find \'$(2)\'"; \
 		ls $$(dirname $(2)); \
 		false; \
 	}
 	grep $(1) $(2) > /dev/null || { \
-		echo "Couldn't" find $(1) in $(2):; \
+		echo "Couldn't" find \'$(1)\' in \'$(2)\':; \
+		cat $(2); \
+		false; \
+	}
+endef
+
+define GREP_V=
+	# grep for a string in a file, outputting the whole file if there *is*
+	# a match.
+	[ -e $(2) ] || { \
+		echo "can't find \'$(2)\'"; \
+		ls $$(dirname $(2)); \
+		false; \
+	}
+	grep -v $(1) $(2) > /dev/null || { \
+		echo Found \'$(1)\' in \'$(2)\':; \
 		cat $(2); \
 		false; \
 	}
