More tests

diff --git a/integtest/Makefile b/integtest/Makefile
--- a/integtest/Makefile
+++ b/integtest/Makefile
@@ -15,7 +15,8 @@ check: \
 	readme_expected_files readme_same_files \
 	simple_all_expected_files \
 	keep_hash_expected_files \
-	sub_dir_expected_files
+	sub_dir_expected_files \
+	keep_hash_and_sub_dir_expected_files
 
 .PHONY: style
 style: html_diff
@@ -83,8 +84,8 @@ endef
 .PHONY: simple_all_expected_files
 simple_all_expected_files:
 	# Test the simplest possible `--all` invocation
-	$(call BUILD_MINIMAL_ALL,/tmp/small_all)
-	$(call MINIMAL_ALL_EXPECTED_FILES,/tmp/small_all)
+	$(call BUILD_MINIMAL_ALL,/tmp/simple_all)
+	$(call MINIMAL_ALL_EXPECTED_FILES,/tmp/simple_all)
 
 .PHONY: keep_hash_expected_files
 keep_hash_expected_files:
@@ -99,9 +100,9 @@ keep_hash_expected_files:
 
 	# Rebuild the docs with --keep_hash which should ignore the replacement
 	/docs_build/build_docs.pl --in_standard_docker --all --push \
-		--keep_hash \
 		--target_repo /tmp/keep_hash.git \
-		--conf small_conf.yaml | tee /tmp/out
+		--conf small_conf.yaml \
+		--keep_hash | tee /tmp/out
 	$(call GREP,'No changes to push',/tmp/out)
 
 	# We expact the same files as the minimal because we the changes that we
@@ -132,10 +133,55 @@ sub_dir_expected_files:
 
 	$(call MINIMAL_ALL_EXPECTED_FILES,/tmp/sub_dir)
 
+keep_hash_and_sub_dir_expected_files:
+	# Test that `--all --keep_hash --sub_dir` keeps hashes the same for repos
+	# not specified by --sub_dir but forces rebuilding all books that include
+	# --sub_dir.
+
+	$(call INIT_REPO_WITH_FILE,/tmp/source1,includes_source2.asciidoc,index.asciidoc)
+	$(call INIT_REPO_WITH_FILE,/tmp/source2,included.asciidoc,index.asciidoc)
+	git init --bare /tmp/keep_hash_and_sub_dir.git
+
+	/docs_build/build_docs.pl --in_standard_docker --all --push \
+		--target_repo /tmp/keep_hash_and_sub_dir.git \
+		--conf two_repos_conf.yaml
+
+	# Move a "bad" file into source2 so we can be sure we're not picking it up
+	cp ../README.asciidoc /tmp/source2/index.asciidoc
+	cd /tmp/source2 && \
+		git add . && \
+		git commit -m 'README'
+
+	/docs_build/build_docs.pl --in_standard_docker --all --push \
+		--target_repo /tmp/keep_hash_and_sub_dir.git \
+		--conf two_repos_conf.yaml \
+		--keep_hash | tee /tmp/out
+	$(call GREP,'No changes to push',/tmp/out)
+
+	# Setup the directory we'd like to substitute
+	rm -rf /tmp/to_sub
+	mkdir /tmp/to_sub
+	cp includes_source2.asciidoc /tmp/to_sub/index.asciidoc
+	echo "extra extra extra" >> /tmp/to_sub/index.asciidoc
+
+	/docs_build/build_docs.pl --in_standard_docker --all --push \
+		--target_repo /tmp/keep_hash_and_sub_dir.git \
+		--conf two_repos_conf.yaml \
+		--keep_hash --sub_dir source1:master:/tmp/to_sub | tee /tmp/out
+	$(call GREP,'Pushing changes',/tmp/out)
+
+	git clone /tmp/keep_hash_and_sub_dir.git /tmp/keep_hash_and_sub_dir
+	$(call GREP,'extra extra extra',/tmp/keep_hash_and_sub_dir/html/test/current/_chapter.html)
+
 
 define GREP=
 	# grep for a string in a file, outputting the whole file if there isn't
 	# a match.
+	[ -e $(2) ] || { \
+		echo "can't find $(2)"; \
+		ls $$(dirname $(2)); \
+		false; \
+	}
 	grep $(1) $(2) > /dev/null || { \
 		echo "Couldn't find $(1) in $(2):"; \
 		cat $(2); \
@@ -147,12 +193,7 @@ define BUILD_MINIMAL_ALL=
 	# Builds `--all` docs using a "minimal" source file
 
 	# First build a repository to use as the source.
-	rm -rf /tmp/source
-	git init /tmp/source
-	cp minimal.asciidoc /tmp/source/index.asciidoc
-	cd /tmp/source && \
-		git add . && \
-		git commit -m 'minimal'
+	$(call INIT_REPO_WITH_FILE,/tmp/source,minimal.asciidoc,index.asciidoc)
 
 	# Initialize a bare repository that the docs build process can use as a
 	# remote. It is used to pushing to github but it can push to a remote on
@@ -173,4 +214,15 @@ define MINIMAL_ALL_EXPECTED_FILES=
 	$(call GREP,'<a class="ulink" href="test/current/index.html" target="_top">Test book</a>',$(1)/html/index.html)
 	$(call GREP,'<meta http-equiv="refresh" content="0; url=current/index.html">',$(1)/html/test/index.html)
 	[ -s $(1)/html/test/current/index.html ]
+endef
+
+define INIT_REPO_WITH_FILE=
+	# Initializes the repo at $(1) and commits the file in $(2) with the
+	# name $(3)
+	rm -rf $(1)
+	git init $(1)
+	cp $(2) $(1)/$(3)
+	cd $(1) && \
+		git add . && \
+		git commit -m 'init'
 endef
